carpentry: swc
title: Побудова графіків і програмування на Python
created: '2016-01-07'
keywords: software, data, lesson, The Carpentries
life_cycle: stable
license: CC-BY 4.0
source: https://github.com/ukrainian-carpentries/python-novice-gapminder
branch: main
contact: team@carpentries.org
episodes:
- 01-run-quit.md
- 02-variables.md
- 03-types-conversion.md
- 04-built-in.md
- 05-coffee.md
- 06-libraries.md
- 07-reading-tabular.md
- 08-data-frames.md
- 09-plotting.md
- 10-lunch.md
- 11-lists.md
- 12-for-loops.md
- 13-conditionals.md
- 14-looping-data-sets.md
- 15-coffee.md
- 16-writing-functions.md
- 17-scope.md
- 18-style.md
- 19-wrap.md
- 20-feedback.md
learners: ~
instructors: ~
profiles: ~
url: https://ukrainian-carpentries.github.io/python-novice-gapminder/
analytics: carpentries
lang: uk
